export const SITE_URL = 'https://moonaesthetic.in';
export const CLINIC_NAME = 'Moon Aesthetic';
export const LOGO_URL = 'https://i.ibb.co/JjPfGgCc/moon-aesthetic-logo.png';
export const DEFAULT_OG_IMAGE = `${SITE_URL}/images/Hero_banner.png`;

export const clinic = {
  name: CLINIC_NAME,
  url: SITE_URL,
  logo: LOGO_URL,
  phone: '+91 9113869966',
  telephone: '+919113869966',
  email: 'info@moonaesthetic.in',
  address: {
    streetAddress: '2nd Floor, Manjaly Edifice, 703, 3rd Cross Road, HRBR Layout 1st Block, Kalyan Nagar',
    addressLocality: 'Bengaluru',
    addressRegion: 'Karnataka',
    postalCode: '560043',
    addressCountry: 'IN',
  },
  geo: { latitude: 13.0213, longitude: 77.6478 },
  openingHours: ['Mo-Su 10:00-19:00'],
  sameAs: [
    'https://www.instagram.com/moonaesthetic.in/',
    'https://www.facebook.com/people/Moon-Aesthetic/61580223223527/',
  ],
  specialties: ['Dermatology', 'Cosmetology', 'Aesthetic Medicine', 'Hair Restoration', 'Laser Hair Removal'],
  areaServed: ['Bengaluru', 'Kalyan Nagar', 'HRBR Layout', 'Karnataka'],
};

export type Treatment = {
  id: number;
  title: string;
  slug: string;
  description: string;
  category: string;
  icon_name: string;
  image_url: string;
  benefits: string[];
  procedure: string[];
  faqs: { question: string; answer: string }[];
  related: string[];
  keywords: string[];
};

export const treatments: Treatment[] = [
  { id: 1, title: 'Skin Consultation', slug: 'skin-consultation', description: 'Comprehensive skin analysis and personalized treatment planning by our expert cosmetologists.', icon_name: 'eye', image_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Personalized skin assessment', 'Customized treatment roadmap', 'Doctor-led recommendations'], procedure: ['Detailed concern review', 'Skin analysis and medical history', 'Personalized care plan with follow-up guidance'], faqs: [{question:'Who should book a skin consultation?',answer:'Anyone with acne, pigmentation, dullness, sensitivity, ageing concerns, or questions about preventive skin care can benefit from a consultation.'}], related:['acne-treatment','pigmentation-treatment','hydrafacial'], keywords:['skin consultation Bangalore','aesthetic clinic Kalyan Nagar'] },
  { id: 2, title: 'Acne Treatment', slug: 'acne-treatment', description: 'Targeted therapies to treat active acne, reduce inflammation, and prevent future breakouts.', icon_name: 'droplets', image_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Reduces active breakouts', 'Controls oil and inflammation', 'Helps prevent recurrence'], procedure: ['Doctor consultation and acne grading', 'Topical, oral, peel, or device-based protocol as suitable', 'Maintenance plan and lifestyle guidance'], faqs: [{question:'How many acne treatment sessions are needed?',answer:'Mild to moderate acne may improve in 4-6 sessions, while severe acne may require a longer personalized protocol.'}], related:['acne-scar-treatment','chemical-peels','skin-consultation'], keywords:['acne treatment Bangalore','pimple treatment Kalyan Nagar'] },
  { id: 3, title: 'Acne Scar Treatment', slug: 'acne-scar-treatment', description: 'Advanced treatments including microneedling and laser to diminish acne scarring and smooth skin texture.', icon_name: 'sparkles', image_url: 'https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Improves scar depth and texture', 'Stimulates collagen remodeling', 'Smooths uneven skin'], procedure: ['Scar type assessment', 'MNRF, microneedling, laser, or peels based on scar pattern', 'Recovery and sunscreen guidance'], faqs: [{question:'Can acne scars be completely removed?',answer:'Acne scars can often be significantly improved, though complete removal depends on scar depth, skin type, and response to treatment.'}], related:['mnrf-treatment','chemical-peels','skin-rejuvenation'], keywords:['acne scar treatment Bangalore','MNRF for scars'] },
  { id: 4, title: 'Pigmentation Treatment', slug: 'pigmentation-treatment', description: 'Effective solutions for melasma, sun spots, and uneven skin tone using laser and chemical treatments.', icon_name: 'sun', image_url: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Targets dark spots and melasma', 'Improves uneven tone', 'Supports brighter-looking skin'], procedure: ['Pigmentation diagnosis', 'Peels, laser, skincare, or combination therapy', 'Sun-protection and maintenance plan'], faqs: [{question:'Is pigmentation treatment safe?',answer:'Yes, treatment selection is customized to skin type and pigmentation cause to prioritize safe, natural improvement.'}], related:['chemical-peels','carbon-facial','skin-consultation'], keywords:['pigmentation treatment Bangalore','melasma treatment'] },
  { id: 5, title: 'Hydrafacial', slug: 'hydrafacial', description: 'Multi-step hydration treatment that cleanses, exfoliates, extracts, and hydrates for instant glow.', icon_name: 'droplets', image_url: 'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Instant glow', 'Deep cleansing and hydration', 'Minimal downtime'], procedure: ['Cleanse and exfoliate', 'Gentle extraction', 'Hydrating serum infusion'], faqs: [{question:'Is Hydrafacial good before an event?',answer:'Hydrafacial is commonly chosen before events because it refreshes skin with little to no downtime.'}], related:['skin-rejuvenation','chemical-peels','carbon-facial'], keywords:['Hydrafacial Bangalore','skin glow facial'] },
  { id: 6, title: 'Chemical Peels', slug: 'chemical-peels', description: 'Medical-grade peels to resurface skin, reduce blemishes, and reveal a brighter, smoother complexion.', icon_name: 'flame', image_url: 'https://images.unsplash.com/photo-1607969341901-1a1e8e22b5f1?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Resurfaces dull skin', 'Helps acne and pigmentation', 'Improves texture'], procedure: ['Skin prep and cleanse', 'Application of suitable peel strength', 'Neutralization and aftercare'], faqs: [{question:'What is the downtime after a chemical peel?',answer:'Light peels may have minimal downtime; medium peels can require several days depending on the peel selected.'}], related:['acne-treatment','pigmentation-treatment','skin-rejuvenation'], keywords:['chemical peel Bangalore','medical grade peels'] },
  { id: 7, title: 'Carbon Facial', slug: 'carbon-facial', description: 'Laser carbon peel treatment for deep pore cleansing, oil reduction, and skin rejuvenation.', icon_name: 'wind', image_url: 'https://images.unsplash.com/photo-1515377905703-c4788f09f098?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Deep pore cleansing', 'Oil reduction', 'Brighter texture'], procedure: ['Carbon application', 'Laser pass over treatment area', 'Cooling and sunscreen aftercare'], faqs: [{question:'Who can choose a carbon facial?',answer:'It suits many people with oily skin, clogged pores, dullness, or mild textural concerns after consultation.'}], related:['hydrafacial','laser-hair-removal','skin-rejuvenation'], keywords:['carbon facial Bangalore','laser carbon peel'] },
  { id: 8, title: 'Skin Rejuvenation', slug: 'skin-rejuvenation', description: 'Comprehensive treatments to restore youthful vitality, improve texture, and revitalize dull skin.', icon_name: 'sparkles', image_url: 'https://images.unsplash.com/photo-1559599076-9c61d8e1b77c?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Improves glow and texture', 'Supports collagen renewal', 'Customizable protocols'], procedure: ['Concern mapping', 'Facial, peel, laser, PRP, or MNRF plan', 'Maintenance scheduling'], faqs: [{question:'What treatments are used for skin rejuvenation?',answer:'Options may include Hydrafacial, peels, carbon facial, PRP, MNRF, and other doctor-recommended procedures.'}], related:['hydrafacial','prp-therapy','mnrf-treatment'], keywords:['skin rejuvenation Bangalore','glowing skin treatment'] },
  { id: 9, title: 'Anti-Aging Treatments', slug: 'anti-aging-treatments', description: 'Botox, fillers, and non-surgical solutions to reduce fine lines, wrinkles, and restore youthful contours.', icon_name: 'clock', image_url: 'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1600&q=80', category: 'Anti-Aging', benefits: ['Softens fine lines', 'Supports youthful contours', 'Natural-looking results'], procedure: ['Facial assessment', 'Botox, fillers, rejuvenation, or combination plan where appropriate', 'Post-procedure guidance'], faqs: [{question:'Will anti-aging treatment look natural?',answer:'Moon Aesthetic focuses on subtle, natural-looking enhancement through conservative, personalized planning.'}], related:['skin-rejuvenation','prp-therapy','hydrafacial'], keywords:['anti aging treatment Bangalore','Botox fillers Bangalore'] },
  { id: 10, title: 'PRP Therapy', slug: 'prp-therapy', description: "Platelet-rich plasma therapy for skin rejuvenation and hair restoration using your body's own growth factors.", icon_name: 'syringe', image_url: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Uses your own platelets', 'Supports hair and skin renewal', 'Natural regenerative approach'], procedure: ['Blood draw and PRP preparation', 'Targeted injections into scalp or skin', 'Session schedule and aftercare'], faqs: [{question:'How does PRP therapy work?',answer:'PRP uses concentrated platelets from your blood to deliver growth factors that support repair and regeneration.'}], related:['hair-regrowth-treatment','gfc-treatment','skin-rejuvenation'], keywords:['PRP treatment Bangalore','PRP hair therapy'] },
  { id: 11, title: 'Hair Fall Treatment', slug: 'hair-fall-treatment', description: 'Medical-grade treatments to address hair thinning and excessive hair fall with proven therapies.', icon_name: 'scissors', image_url: 'https://images.unsplash.com/photo-1519735777090-ec97162dc266?auto=format&fit=crop&w=1600&q=80', category: 'Hair', benefits: ['Targets hair fall causes', 'Strengthens existing hair', 'Doctor-led scalp care'], procedure: ['Hair and scalp diagnosis', 'Medical, topical, PRP, GFC, or combination plan', 'Progress tracking'], faqs: [{question:'Can hair fall be controlled?',answer:'Many forms of hair fall can be controlled with correct diagnosis and a consistent treatment plan.'}], related:['hair-regrowth-treatment','prp-therapy','anti-dandruff-treatment'], keywords:['hair fall treatment Bangalore','hair loss clinic Kalyan Nagar'] },
  { id: 12, title: 'Hair Regrowth Treatment', slug: 'hair-regrowth-treatment', description: 'Advanced regrowth protocols combining PRP, mesotherapy, and topical treatments for denser, healthier hair.', icon_name: 'heartpulse', image_url: 'https://images.unsplash.com/photo-1595475884562-073c30d45670?auto=format&fit=crop&w=1600&q=80', category: 'Hair', benefits: ['Encourages regrowth', 'Improves density appearance', 'Customized combination therapy'], procedure: ['Scalp and history evaluation', 'PRP, GFC, mesotherapy, or topical plan', 'Follow-up and maintenance'], faqs: [{question:'When will I see hair regrowth results?',answer:'Visible improvement varies, but regenerative hair plans are usually assessed over multiple months and sessions.'}], related:['hair-fall-treatment','prp-therapy','gfc-treatment'], keywords:['hair regrowth treatment Bangalore','PRP GFC hair'] },
  { id: 13, title: 'Laser Hair Removal', slug: 'laser-hair-removal', description: 'Safe and effective permanent hair reduction using advanced laser technology for all skin types.', icon_name: 'zap', image_url: 'https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?auto=format&fit=crop&w=1600&q=80', category: 'Laser', benefits: ['Long-term hair reduction', 'Suitable planning for different skin types', 'Smoother skin with less ingrowth'], procedure: ['Consultation and patch planning', 'Laser session with cooling support', 'Multiple sessions and aftercare guidance'], faqs: [{question:'Is laser hair removal safe for all skin types?',answer:'Advanced laser technology can be used safely for many skin types after doctor assessment and parameter customization.'}], related:['carbon-facial','skin-consultation','skin-rejuvenation'], keywords:['Laser Hair Removal in Bangalore','permanent hair reduction Kalyan Nagar'] },
  { id: 14, title: 'IV Infusion Therapy', slug: 'iv-infusion-therapy', description: 'Intravenous vitamin and nutrient infusions for skin glow, immunity boost, and overall wellness.', icon_name: 'syringe', image_url: 'https://images.unsplash.com/photo-1631815588090-d4bfec5b1ccb?auto=format&fit=crop&w=1600&q=80', category: 'Wellness', benefits: ['Wellness support', 'Skin glow protocols', 'Clinically supervised infusion'], procedure: ['Health and suitability check', 'IV infusion administration', 'Post-infusion observation'], faqs: [{question:'Who can take IV infusion therapy?',answer:'Suitability depends on health history and goals, so a clinic consultation is required before infusion therapy.'}], related:['skin-rejuvenation','hydrafacial','skin-consultation'], keywords:['IV infusion therapy Bangalore','glow drip Bangalore'] },
  { id: 15, title: 'MNRF Treatment', slug: 'mnrf-treatment', description: 'Microneedling Radiofrequency (MNRF) combines micro-injuries with RF energy to stimulate collagen, tighten skin, and reduce scars and pores.', icon_name: 'sparkles', image_url: 'https://images.unsplash.com/photo-1607962837359-5e7e89f86776?auto=format&fit=crop&w=1600&q=80', category: 'Skin', benefits: ['Improves acne scars and pores', 'Stimulates collagen', 'Tightens skin texture'], procedure: ['Numbing and skin preparation', 'MNRF passes at planned depth', 'Healing and sun-care instructions'], faqs: [{question:'What is MNRF used for?',answer:'MNRF is commonly used for acne scars, enlarged pores, texture, and skin tightening after suitability assessment.'}], related:['acne-scar-treatment','skin-rejuvenation','prp-therapy'], keywords:['MNRF treatment Bangalore','microneedling RF'] },
  { id: 16, title: 'GFC Treatment', slug: 'gfc-treatment', description: 'Growth Factor Concentrate (GFC) therapy uses your own concentrated growth factors to promote hair regrowth and skin rejuvenation.', icon_name: 'syringe', image_url: 'https://images.unsplash.com/photo-1626278664285-f796b9ee7806?auto=format&fit=crop&w=1600&q=80', category: 'Hair', benefits: ['Growth factor-rich therapy', 'Supports hair regrowth', 'Autologous regenerative care'], procedure: ['Blood collection', 'GFC preparation', 'Targeted scalp or skin delivery'], faqs: [{question:'How is GFC different from PRP?',answer:'GFC uses a concentrated growth-factor preparation from your blood and may be recommended based on hair or skin goals.'}], related:['prp-therapy','hair-regrowth-treatment','hair-fall-treatment'], keywords:['GFC treatment Bangalore','growth factor concentrate hair'] },
  { id: 17, title: 'Anti Dandruff Treatment', slug: 'anti-dandruff-treatment', description: 'Targeted scalp treatments to eliminate dandruff, soothe irritation, and restore a healthy, flake-free scalp.', icon_name: 'droplets', image_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=1600&q=80', category: 'Hair', benefits: ['Reduces flakes and itch', 'Soothes scalp irritation', 'Supports healthier scalp'], procedure: ['Scalp assessment', 'Medicated and procedural scalp care as needed', 'Maintenance routine guidance'], faqs: [{question:'Can dandruff come back?',answer:'Dandruff can recur, but the right diagnosis, treatment, and maintenance scalp care can reduce flares.'}], related:['hair-fall-treatment','hair-regrowth-treatment','skin-consultation'], keywords:['anti dandruff treatment Bangalore','scalp treatment Kalyan Nagar'] },
];

export const doctors = [
  { name: 'Dr. Syed Anjum', slug: 'dr-syed-anjum', qualification: 'MBBS', designation: 'Consultant Cosmetologist', image: 'https://i.ibb.co/Kp16qZ8Q/sayyed-anjum.webp', specialties: ['Aesthetic Medicine', 'Skin Rejuvenation', 'Hair Restoration', 'Laser Treatments'] },
  { name: 'Dr. Hiba Perween', slug: 'dr-hiba-perween', qualification: 'Cosmetologist', designation: 'Skin & Hair Expert', image: 'https://i.ibb.co/ynCk7ybv/Hiba.webp', specialties: ['Cosmetology', 'Skin Treatments', 'Hair Treatments'] },
];

export const pages = [
  { slug: '', path: '/', title: 'Moon Aesthetic | Skin, Hair & Aesthetic Clinic Bangalore', description: 'Moon Aesthetic is an advanced skin, hair and aesthetic clinic in Kalyan Nagar, Bengaluru offering laser hair removal, PRP, MNRF, acne, pigmentation, anti-aging and wellness treatments.', keywords: ['Moon Aesthetic', 'skin clinic Bangalore', 'aesthetic clinic Bengaluru'], image: DEFAULT_OG_IMAGE },
  { slug: 'about', path: '/about', title: 'About Moon Aesthetic | Aesthetic Clinic in Kalyan Nagar', description: 'Learn about Moon Aesthetic, an advanced skin, hair and aesthetic clinic in Kalyan Nagar, Bengaluru focused on safe, personalized and evidence-based treatments.', keywords: ['about Moon Aesthetic', 'aesthetic doctors Bangalore'], image: `${SITE_URL}/images/About_page.jpeg` },
  { slug: 'treatments', path: '/treatments', title: 'Skin, Hair & Laser Treatments in Bangalore | Moon Aesthetic', description: 'Explore Moon Aesthetic treatments including acne care, pigmentation, Hydrafacial, chemical peels, laser hair removal, PRP, GFC, MNRF and anti-aging care.', keywords: ['skin treatments Bangalore', 'hair treatments Bangalore', 'laser treatments Bangalore'], image: `${SITE_URL}/images/service-skin.jpg` },
  { slug: 'contact', path: '/contact', title: 'Contact Moon Aesthetic | Book Appointment in Kalyan Nagar', description: 'Contact Moon Aesthetic in Kalyan Nagar, Bengaluru to book skin, hair, laser, anti-aging and wellness consultations with experienced aesthetic doctors.', keywords: ['Moon Aesthetic contact', 'book skin clinic Bangalore'], image: `${SITE_URL}/images/clinic-interior.jpg` },
];

export const getTreatment = (slug?: string) => treatments.find((t) => t.slug === slug);
export const toAbsoluteUrl = (path: string) => path.startsWith('http') ? path : `${SITE_URL}${path}`;
