const SITE_URL = 'https://moonaesthetic.in';
const pages = [
  { slug: '', canonical: `${SITE_URL}/`, title: 'Moon Aesthetic | Skin, Hair & Aesthetic Clinic Bangalore', description: 'Moon Aesthetic is an advanced skin, hair and aesthetic clinic in Kalyan Nagar, Bengaluru offering laser hair removal, PRP, MNRF, acne, pigmentation, anti-aging and wellness treatments.', openGraphImage: `${SITE_URL}/images/Hero_banner.png` },
  { slug: 'about', canonical: `${SITE_URL}/about`, title: 'About Moon Aesthetic | Aesthetic Clinic in Kalyan Nagar', description: 'Learn about Moon Aesthetic, an advanced skin, hair and aesthetic clinic in Kalyan Nagar, Bengaluru focused on safe, personalized and evidence-based treatments.', openGraphImage: `${SITE_URL}/images/About_page.jpeg` },
  { slug: 'treatments', canonical: `${SITE_URL}/treatments`, title: 'Skin, Hair & Laser Treatments in Bangalore | Moon Aesthetic', description: 'Explore Moon Aesthetic treatments including acne care, pigmentation, Hydrafacial, chemical peels, laser hair removal, PRP, GFC, MNRF and anti-aging care.', openGraphImage: `${SITE_URL}/images/service-skin.jpg` },
  { slug: 'contact', canonical: `${SITE_URL}/contact`, title: 'Contact Moon Aesthetic | Book Appointment in Kalyan Nagar', description: 'Contact Moon Aesthetic in Kalyan Nagar, Bengaluru to book skin, hair, laser, anti-aging and wellness consultations with experienced aesthetic doctors.', openGraphImage: `${SITE_URL}/images/clinic-interior.jpg` },
];
const treatments = [
  { slug: 'skin-consultation', canonical: `${SITE_URL}/treatments/skin-consultation`, title: 'Skin Consultation in Bangalore | Moon Aesthetic', description: 'Comprehensive skin analysis and personalized treatment planning by our expert cosmetologists.', openGraphImage: `${SITE_URL}/images/service-skin.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Skin Consultation', description: 'Comprehensive skin analysis and personalized treatment planning by our expert cosmetologists.' } },
  { slug: 'acne-treatment', canonical: `${SITE_URL}/treatments/acne-treatment`, title: 'Acne Treatment in Bangalore | Moon Aesthetic', description: 'Targeted therapies to treat active acne, reduce inflammation, and prevent future breakouts.', openGraphImage: `${SITE_URL}/images/service-skin.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Acne Treatment', description: 'Targeted therapies to treat active acne, reduce inflammation, and prevent future breakouts.' } },
  { slug: 'acne-scar-treatment', canonical: `${SITE_URL}/treatments/acne-scar-treatment`, title: 'Acne Scar Treatment in Bangalore | Moon Aesthetic', description: 'Advanced treatments including microneedling and laser to diminish acne scarring and smooth skin texture.', openGraphImage: `${SITE_URL}/images/service-skin.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Acne Scar Treatment', description: 'Advanced treatments including microneedling and laser to diminish acne scarring and smooth skin texture.' } },
  { slug: 'pigmentation-treatment', canonical: `${SITE_URL}/treatments/pigmentation-treatment`, title: 'Pigmentation Treatment in Bangalore | Moon Aesthetic', description: 'Effective solutions for melasma, sun spots, and uneven skin tone using laser and chemical treatments.', openGraphImage: `${SITE_URL}/images/service-skin.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Pigmentation Treatment', description: 'Effective solutions for melasma, sun spots, and uneven skin tone using laser and chemical treatments.' } },
  { slug: 'hydrafacial', canonical: `${SITE_URL}/treatments/hydrafacial`, title: 'Hydrafacial in Bangalore | Moon Aesthetic', description: 'Multi-step hydration treatment that cleanses, exfoliates, extracts, and hydrates for instant glow.', openGraphImage: `${SITE_URL}/images/service-skin.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Hydrafacial', description: 'Multi-step hydration treatment that cleanses, exfoliates, extracts, and hydrates for instant glow.' } },
  { slug: 'chemical-peels', canonical: `${SITE_URL}/treatments/chemical-peels`, title: 'Chemical Peels in Bangalore | Moon Aesthetic', description: 'Medical-grade peels to resurface skin, reduce blemishes, and reveal a brighter, smoother complexion.', openGraphImage: `${SITE_URL}/images/service-peels.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Chemical Peels', description: 'Medical-grade peels to resurface skin, reduce blemishes, and reveal a brighter, smoother complexion.' } },
  { slug: 'carbon-facial', canonical: `${SITE_URL}/treatments/carbon-facial`, title: 'Carbon Facial in Bangalore | Moon Aesthetic', description: 'Laser carbon peel treatment for deep pore cleansing, oil reduction, and skin rejuvenation.', openGraphImage: `${SITE_URL}/images/service-laser.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Carbon Facial', description: 'Laser carbon peel treatment for deep pore cleansing, oil reduction, and skin rejuvenation.' } },
  { slug: 'skin-rejuvenation', canonical: `${SITE_URL}/treatments/skin-rejuvenation`, title: 'Skin Rejuvenation in Bangalore | Moon Aesthetic', description: 'Comprehensive treatments to restore youthful vitality, improve texture, and revitalize dull skin.', openGraphImage: `${SITE_URL}/images/service-antiaging.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Skin Rejuvenation', description: 'Comprehensive treatments to restore youthful vitality, improve texture, and revitalize dull skin.' } },
  { slug: 'anti-aging-treatments', canonical: `${SITE_URL}/treatments/anti-aging-treatments`, title: 'Anti-Aging Treatments in Bangalore | Moon Aesthetic', description: 'Botox, fillers, and non-surgical solutions to reduce fine lines, wrinkles, and restore youthful contours.', openGraphImage: `${SITE_URL}/images/service-antiaging.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Anti-Aging Treatments', description: 'Botox, fillers, and non-surgical solutions to reduce fine lines, wrinkles, and restore youthful contours.' } },
  { slug: 'prp-therapy', canonical: `${SITE_URL}/treatments/prp-therapy`, title: 'PRP Therapy in Bangalore | Moon Aesthetic', description: "Platelet-rich plasma therapy for skin rejuvenation and hair restoration using your body's own growth factors.", openGraphImage: `${SITE_URL}/images/service-prp.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'PRP Therapy', description: "Platelet-rich plasma therapy for skin rejuvenation and hair restoration using your body's own growth factors." } },
  { slug: 'hair-fall-treatment', canonical: `${SITE_URL}/treatments/hair-fall-treatment`, title: 'Hair Fall Treatment in Bangalore | Moon Aesthetic', description: 'Medical-grade treatments to address hair thinning and excessive hair fall with proven therapies.', openGraphImage: `${SITE_URL}/images/service-hair.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Hair Fall Treatment', description: 'Medical-grade treatments to address hair thinning and excessive hair fall with proven therapies.' } },
  { slug: 'hair-regrowth-treatment', canonical: `${SITE_URL}/treatments/hair-regrowth-treatment`, title: 'Hair Regrowth Treatment in Bangalore | Moon Aesthetic', description: 'Advanced regrowth protocols combining PRP, mesotherapy, and topical treatments for denser, healthier hair.', openGraphImage: `${SITE_URL}/images/service-hair.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Hair Regrowth Treatment', description: 'Advanced regrowth protocols combining PRP, mesotherapy, and topical treatments for denser, healthier hair.' } },
  { slug: 'laser-hair-removal', canonical: `${SITE_URL}/treatments/laser-hair-removal`, title: 'Laser Hair Removal in Bangalore | Moon Aesthetic', description: 'Safe and effective permanent hair reduction using advanced laser technology for all skin types.', openGraphImage: `${SITE_URL}/images/service-laser.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Laser Hair Removal', description: 'Safe and effective permanent hair reduction using advanced laser technology for all skin types.' } },
  { slug: 'iv-infusion-therapy', canonical: `${SITE_URL}/treatments/iv-infusion-therapy`, title: 'IV Infusion Therapy in Bangalore | Moon Aesthetic', description: 'Intravenous vitamin and nutrient infusions for skin glow, immunity boost, and overall wellness.', openGraphImage: `${SITE_URL}/images/service-skin.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'IV Infusion Therapy', description: 'Intravenous vitamin and nutrient infusions for skin glow, immunity boost, and overall wellness.' } },
  { slug: 'mnrf-treatment', canonical: `${SITE_URL}/treatments/mnrf-treatment`, title: 'MNRF Treatment in Bangalore | Moon Aesthetic', description: 'Microneedling Radiofrequency (MNRF) combines micro-injuries with RF energy to stimulate collagen, tighten skin, and reduce scars and pores.', openGraphImage: `${SITE_URL}/images/service-mnrf.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'MNRF Treatment', description: 'Microneedling Radiofrequency (MNRF) combines micro-injuries with RF energy to stimulate collagen, tighten skin, and reduce scars and pores.' } },
  { slug: 'gfc-treatment', canonical: `${SITE_URL}/treatments/gfc-treatment`, title: 'GFC Treatment in Bangalore | Moon Aesthetic', description: 'Growth Factor Concentrate (GFC) therapy uses your own concentrated growth factors to promote hair regrowth and skin rejuvenation.', openGraphImage: `${SITE_URL}/images/service-gfc.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'GFC Treatment', description: 'Growth Factor Concentrate (GFC) therapy uses your own concentrated growth factors to promote hair regrowth and skin rejuvenation.' } },
  { slug: 'anti-dandruff-treatment', canonical: `${SITE_URL}/treatments/anti-dandruff-treatment`, title: 'Anti Dandruff Treatment in Bangalore | Moon Aesthetic', description: 'Targeted scalp treatments to eliminate dandruff, soothe irritation, and restore a healthy, flake-free scalp.', openGraphImage: `${SITE_URL}/images/service-antidandruff.jpg`, schema: { '@context': 'https://schema.org', '@type': 'Service', name: 'Anti Dandruff Treatment', description: 'Targeted scalp treatments to eliminate dandruff, soothe irritation, and restore a healthy, flake-free scalp.' } }
];
export default function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Use POST for GraphQL queries.' });
  const query = req.body?.query || '';
  const slug = req.body?.variables?.slug || query.match(/pageSEO\(slug:\s*"([^"]+)"\)/)?.[1] || '';
  const data = [...pages, ...treatments].find((p) => p.slug === slug);
  return res.status(200).json({ data: { pageSEO: data || null } });
}
